import 'dart:convert';
import 'dart:io';

const workspaceRoot = '.';
const manifestPath =
    'packages/app_shell/lib/src/tool_manifest.g.dart';

void main() {
  final pubspec = File('$workspaceRoot/pubspec.yaml').readAsStringSync();
  final packages = _parseWorkspacePackages(pubspec);
  final pluginEntries = <PluginEntry>[];

  for (final pkg in packages) {
    final pluginFile = File('$workspaceRoot/$pkg/lib/plugin.dart');
    if (!pluginFile.existsSync()) continue;

    final pubspecFile = File('$workspaceRoot/$pkg/pubspec.yaml');
    final packageName = _parsePackageName(pubspecFile.readAsStringSync());

    pluginEntries.add(PluginEntry(
      packageName: packageName,
      sourceUri: 'package:$packageName/plugin.dart',
    ));
  }

  pluginEntries.sort((a, b) => a.packageName.compareTo(b.packageName));

  final buffer = StringBuffer();
  buffer.writeln('// Generated by scripts/plugin_manifest.dart');
  buffer.writeln('// Do not edit by hand — run `melos run generate-plugins` to regenerate.');
  buffer.writeln();
  buffer.writeln("import 'package:core_plugin_api/core_plugin_api.dart';");
  buffer.writeln();
  for (final entry in pluginEntries) {
    buffer.writeln("import '${entry.sourceUri}' as ${entry.packageName.replaceAll('-', '_')};");
  }
  buffer.writeln();
  buffer.writeln('const allToolPlugins = <ToolPlugin>[');
  for (final entry in pluginEntries) {
    buffer.writeln('  ${entry.packageName.replaceAll('-', '_')}.plugin,');
  }
  buffer.writeln('];');

  File(manifestPath).writeAsStringSync(buffer.toString());
  print('Generated $manifestPath with ${pluginEntries.length} plugin(s):');
  for (final entry in pluginEntries) {
    print('  - ${entry.packageName}');
  }
}

class PluginEntry {
  final String packageName;
  final String sourceUri;

  const PluginEntry({required this.packageName, required this.sourceUri});
}

String _parsePackageName(String pubspecYaml) {
  final nameMatch = RegExp(r'^name:\s*(\S+)', multiLine: true).firstMatch(pubspecYaml);
  if (nameMatch == null) {
    throw FormatException('Could not find package name in pubspec');
  }
  return nameMatch.group(1)!;
}

List<String> _parseWorkspacePackages(String pubspecYaml) {
  final packages = <String>[];
  final lines = LineSplitter.split(pubspecYaml);
  bool inWorkspace = false;
  for (final line in lines) {
    if (line.trim() == 'workspace:') {
      inWorkspace = true;
      continue;
    }
    if (inWorkspace) {
      final trimmed = line.trimLeft();
      if (trimmed.startsWith('- ')) {
        final pkg = trimmed.substring(2).trim();
        packages.add(pkg);
      } else if (!trimmed.startsWith('-') && trimmed.contains(':')) {
        break;
      }
    }
  }
  return packages;
}
