include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:

custom_lint:
  rules:
    - kitbag_layer_boundary
    - kitbag_ffi_boundary
    - kitbag_provider_location
    - kitbag_naming_convention
